.Dd November 12, 2010
.Dt SEARCH 1
.Os
.Sh NAME
.Nm search
.Nd walk through a file hierarchy
.Sh SYNOPSIS
.Nm
.Op Fl EILPsv
.Ar path ...
.Op Fl n Ar pattern | Fl -name Ar pattern
.Op Fl r Ar regexp | Fl -regex Ar regexp
.Op Fl t Ar ftype | Fl -type Ar ftype
.Op Fl -empty
.Sh DESCRIPTION
The
.Nm
will walk through a file hierachy.
.Pp
Short options:
.Bl -tag -width indent
.It Fl E
use modern regular expressions rather than `basic' (obsolete)
regular expressions which is the default. See the man page of
.Xr re_format 7
for more information.
.It Fl I
case insensitive search, otherwise the specified pattern is
interpreted as case sensitive.
.It Fl L
follow symbolic links and return the information of the files
they reference. It is an error if the referenced files do not
exist.
.It Fl P
do not follow symbolic links, but return the information the
symbolic links themselves, this is the default behaviour.
.It Fl s
cause
.Nm
to alphabetically sort the search results. Note:
.Ql search -s
has identical output as
.Ql search | sort .
.It Fl v
show version number
.It Fl n Ar pattern
specify a
.Ar pattern
to match the search results. Special shell pattern matching
characters may be used as part of the pattern. See the man
page of
.Xr fnmatch 3
for more information.
.It Fl r Ar regexp
specify a regular expression
.Ar regexp
to match the search results. Unless the option
.Ic -E
is explicitly specified, the regular expression will only be
interpreted as
.Ql basic
(obsolete) regular expressions. See the man page of
.Xr re_format 7
for more information.
.It Fl t Ar ftype
specify a file type
.Ar ftype
to match the search results.
.Pp
.Bl -tag -width indent -compact
.It Cm b
block device
.It Cm c
character special
.It Cm d
directory
.It Cm f
fifo
.It Cm l
symbolic link
.It Cm r
regular file
.It Cm s
socket
.It Cm w
white out (OpenBSD doesn't have this)
.El
.El
.Pp
Long options:
.Bl -tag -width indent
.It Fl -empty
find empty files or directories.
.It Fl -name Ar pattern
same as
.Ic -n .
.It Fl -regex Ar regexp
same as
.Ic -r .
.It Fl -type Ar ftype
same as
.Ic -t .
.El
.Sh NOTES
As
.Nm
is just a programming practice work. Now it uses a binary search tree
to sort the search results, which is rather time-cosuming and
memory-intensive for a large file hierachy. For instance, if you run 
.Ql search -s / ,
just get a cup of coffe and read some news before the output should
pop out ...
.Sh HISTORY
A
.Nm
command was written mainly for programming practice.
.Sh AUTHOR
Denise H. G. <darcsis AT gmail DOT com>
.Sh BUGS
There must be plenty of them...
