.Dd November 12, 2010
.Dt SEARCH 1
.Os
.Sh NAME
.Nm search
.Nd walk through a file hierarchy
.Sh SYNOPSIS
.Nm
.Op Fl EHILPshv
.Ar path ...
.Op Fl t Ar ... | Fl \-type Ar ...
.Op Fl r Ar ... | Fl \-regex Ar ...
.Op Fl \-empty
.Sh DESCRIPTION
The
.Nm
will walk through a file hierachy.
.Pp
Short options:
.Bl -tag -width indent
.It Fl h
this long help.
.It Fl v
show version number
.It Fl s
cause
.Nm
to alphabetically sort the search results.
Note: search
.Ic -s
has identical output as `search | sort'.
.It Fl E
use modern regular expressions rather than `basic' (obsolete)
regular expressions which is the default. See the man page of
.Xr re_format 7
for more information.
.It Fl I
case insensitive search, otherwise the specified pattern is
interpreted as case sensitive.
.It Fl P
do not follow symbolic links, but return the information the
symbolic links themselves, this is the default behaviour.
.It Fl L
follow symbolic links and return the information of the files
they reference. It is an error if the referenced files do not
exist.
.It Fl n Ar pattern
specify a
.Ar pattern
to match the search results. Special shell pattern matching
characters may be used as part of the pattern. See the man
page of
.Xr fnmatch 3
for more information.
.It Fl r Ar regexp
specify a regular expression
.Ar regexp
to match the search results. Unless the option
.Ic -E
is explicitly specified, the regular expression will only be
interpreted as `basic' (obsolete) regular expressions. See the
man page of
.Xr re_format 7
for more information.
.It Fl t Ar type
specify a file type
.Ar type
to match the search results.
.Pp
.Bl -tag -width indent -compact
.It Cm b
block device
.It Cm c
character special
.It Cm d
directory
.It Cm f
fifo
.It Cm l
symbolic link
.It Cm r
regular file
.It Cm s
socket
.It Cm w
white out (OpenBSD doesn't have this)
.El
.El
.Pp
Long options:
.Bl -tag -width indent
.It Fl -empty
find empty files or directories.
.It Fl -name Ar pattern
same as
.Ic -n .
.It Fl -regex Ar regexp
same as
.Ic -r .
.El
.Sh HISTORY
A \fBsearch\fR command was written mainly for programming practice.
.Sh AUTHOR
\fBDenise H. G.\fR <darcsis AT gmail DOT com>
.Sh BUGS
There must be some of them...
